export default () => ({
  prod: {
    api_port: 5000,
    webhook_port: 5001,
    aws: {
      AWS_PUBLIC_BUCKET_NAME: 'beckett-marketplace-dev',
    },
    redis: {
      host: 'localhost',
      port: 6379,
    },
    queue: {
      mint: 'beckett_mint_prod',
      burn: 'beckett_burn_prod',
      lock: 'beckett_lock_prod',
      limiter: { max: 1, duration: 10 },
    },
    db: {
      name: 'beckett_prod',
      sync: false,
      host: 'prod-beckett-vaulting-database.cluster-cgq6lc7ttzjk.us-west-1.rds.amazonaws.com',
      port: 3306,
      username: process.env.DB_PROD_USERNAME,
      password: process.env.DB_PROD_PASSWORD,
    },
    blockchain: {
      tx_config: {},
    },
    min_token_id: 1,
    network_mint_relayer: 'polygon_prod_mint',
    network_lock_relayer: 'polygon_prod_lock',
    network_burn_relayer: 'polygon_prod_burn',
    pinata: 'prod',
    webhook_shared_secret: process.env.BECKETT_AUTOTASK_SHARED_SECRET_PROD,
    check_palantir_request_auth: true,
  },
  stage: {
    api_port: 4000,
    webhook_port: 4001,
    aws: {
      AWS_PUBLIC_BUCKET_NAME: 'beckett-marketplace-dev',
    },
    redis: {
      host: 'localhost',
      port: 6379,
    },
    queue: {
      mint: 'beckett_mint_stage',
      burn: 'beckett_burn_stage',
      lock: 'beckett_lock_stage',
      limiter: { max: 1, duration: 10 },
    },
    db: {
      name: 'beckett_stage',
      sync: false,
      host: 'vaulting-api-dev-stage.cluster-cgq6lc7ttzjk.us-west-1.rds.amazonaws.com',
      port: 3306,
      username: process.env.DB_USERNAME,
      password: process.env.DB_PASSWORD,
    },
    blockchain: {
      tx_config: {},
    },
    min_token_id: 1,
    network_mint_relayer: 'polygon_stage',
    pinata: 'stage',
    webhook_shared_secret: process.env.BECKETT_AUTOTASK_SHARED_SECRET,
    check_palantir_request_auth: false,
  },
  awsdev: {
    api_port: 3000,
    webhook_port: 3001,
    auth_enabled: false,
    aws: {
      AWS_PUBLIC_BUCKET_NAME: 'beckett-marketplace-dev',
      AWS_ACCESS_KEY_ID: process.env.MARKETPLACE_AWS_ACCESS_KEY_ID,
      AWS_SECRET_ACCESS_KEY: process.env.MARKETPLACE_AWS_SECRET_ACCESS_KEY,
      AWS_DEFAULT_REGION: 'us-west-1',
    },
    cognito: {
      COGNITO_USER_POOL_ID: 'us-west-1_qhggfzGoG',
      COGNITO_CLIENT_ID: '1ncv47qt6dja3amd6kolhssrts',
      COGNITO_REGION: 'us-west-1',
    },
    redis: {
      host: 'localhost',
      port: 6379,
    },
    queue: {
      mint: 'beckett_mint_dev',
      burn: 'beckett_burn_dev',
      lock: 'beckett_lock_dev',
      limiter: { max: 1, duration: 10 },
    },
    db: {
      name: 'beckett_dev',
      sync: false,
      host: 'vaulting-api-dev-stage.cluster-cgq6lc7ttzjk.us-west-1.rds.amazonaws.com',
      port: 3306,
      username: process.env.DB_USERNAME,
      password: process.env.DB_PASSWORD,
    },
    blockchain: {
      tx_config: {},
    },
    min_token_id: 1000000,
    network_mint_relayer: 'mumbai',
    pinata: 'dev',
    webhook_shared_secret: process.env.BECKETT_AUTOTASK_SHARED_SECRET,
    check_palantir_request_auth: false,
  },
  dev: {
    api_port: 3300,
    webhook_port: 3301,
    auth_enabled: false,
    cognito: {
      COGNITO_USER_POOL_ID: 'us-west-1_qhggfzGoG',
      COGNITO_CLIENT_ID: '1ncv47qt6dja3amd6kolhssrts',
      COGNITO_REGION: 'us-west-1',
    },
    bravo: {
      mint: {
        collection: '0x599b70873851c5ef6d52A613c574D6F688A53524',
        url: 'https://dev.beckett.com:3000/vaulting/mint',
        headers: { 'Content-Type': 'application/json' },
      },
    },
    aws: {
      AWS_PUBLIC_BUCKET_NAME: 'beckett-marketplace-dev',
      AWS_ACCESS_KEY_ID: process.env.MARKETPLACE_AWS_ACCESS_KEY_ID,
      AWS_SECRET_ACCESS_KEY: process.env.MARKETPLACE_AWS_SECRET_ACCESS_KEY,
      AWS_DEFAULT_REGION: 'us-west-1',
    },
    redis: {
      host: 'localhost',
      port: 6379,
    },
    queue: {
      mint: 'beckett_mint_dev',
      burn: 'beckett_burn_dev',
      lock: 'beckett_lock_dev',
      limiter: { max: 1, duration: 10 },
    },
    db: {
      name: 'beckett_marketplace_db_dev.sqlite',
      sync: true,
    },
    blockchain: {
      tx_config: { gasLimit: 200000 },
    },
    min_token_id: 1,
    network_mint_relayer: 'mumbai',
    pinata: 'dev',
    webhook_shared_secret: process.env.BECKETT_AUTOTASK_SHARED_SECRET,
    check_palantir_request_auth: false,
  },
});
